name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        if: ${{ false }} # Set ke true kalau storage kurang
        uses: jlumbroso/free-disk-space@main

      - name: Install Slim LLVM 21.1.2
        run: |
          mkdir -p $HOME/toolchains/llvm-21
          cd $HOME/toolchains/llvm-21
          curl -LO https://mirrors.edge.kernel.org/pub/tools/llvm/files/llvm-21.1.2-x86_64.tar.gz
          tar -xzf llvm-21.1.2-x86_64.tar.gz --strip-components=1

          echo "PATH=$HOME/toolchains/llvm-21/bin:$PATH" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "LD=ld.lld" >> $GITHUB_ENV
          echo "AR=llvm-ar" >> $GITHUB_ENV
          echo "NM=llvm-nm" >> $GITHUB_ENV
          echo "OBJCOPY=llvm-objcopy" >> $GITHUB_ENV
          echo "OBJDUMP=llvm-objdump" >> $GITHUB_ENV
          echo "READELF=llvm-readelf" >> $GITHUB_ENV
          echo "STRIP=llvm-strip" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          chmod +x build.sh
          ./build.sh
