name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        if: ${{ false }} # Set to true if space insufficient
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 7

      - name: Include KernelSU-Next
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf KernelSU 2>/dev/null
          # coba patch dari branch main
          if ! curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/main/kernel/setup.sh" | bash - ; then
            # fallback ke branch next
            curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl make gcc g++ bc bison flex \
            libssl-dev libncurses5-dev libncursesw5-dev \
            python3 unzip device-tree-compiler \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download LLVM 21.1.2
        run: |
          mkdir -p $HOME/toolchains
          cd $HOME/toolchains
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.2/LLVM-21.1.2-Linux-X64.tar.xz
          mkdir -p llvm-21
          tar -xf LLVM-21.1.2-Linux-X64.tar.xz -C llvm-21 --strip-components=1
          ls -l llvm-21/bin

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Compress kernel image
        run: |
          cd build
          gzip -9 -c Image > Image.gz

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: build/Image.gz
